version: '3.8'

services:
  go:
    container_name: "${COMPOSE_PROJECT_NAME}_go"
    build:
      context: ./images/go
    ports:
      - "${HTTP_PORT}:3000"
    volumes:
      - ../:/var/www:delegated
    depends_on:
      - postgres

  postgres:
    container_name: "${COMPOSE_PROJECT_NAME}_postgres"
    build:
      context: ./images/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_MULTIPLE_DATABASES

  minio:
    container_name: "${COMPOSE_PROJECT_NAME}_minio"
    command: server --console-address :9001 /data
    image: minio/minio:latest
    ports:
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD


volumes:
  postgres:
  minio:
